name: ef_env
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.6
  - pytorch=0.4.1
  - torchvision=0.2.1
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - ipykernel
prefix: /home/azureuser/miniconda3/envs/ef_env
